--- 
AWSTemplateFormatVersion: '2010-09-09'
Description: This Stack creates following resources - yet to finalize

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
    Default: nv-kp
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t1.micro, t2.nano, t2.micro, t2.small, t2.medium, t2.large, m1.small]
    ConstraintDescription: must be a valid EC2 instance type.
  ImageId:
    Description: Image ID to launch EC2 instances.
    Type: AWS::EC2::Image::Id
    Default: ami-04681a1dbd79675a5
      
Resources:    
  # Security Group Group and Rules creation
  SecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: "Allow HTTP/(s) SSH"
      SecurityGroupEgress:
        - 
          CidrIp: 0.0.0.0/0
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
        -
          CidrIp: 0.0.0.0/0
          FromPort: "443"
          IpProtocol: tcp
          ToPort: "443"
        -
          CidrIp: 0.0.0.0/0
          FromPort: "18630"
          IpProtocol: tcp
          ToPort: "18630"
      SecurityGroupIngress: 
        - 
          CidrIp: 0.0.0.0/0
          FromPort: "80"
          IpProtocol: tcp
          ToPort: "80"
        - 
          CidrIp: 0.0.0.0/0
          FromPort: "22"
          IpProtocol: tcp
          ToPort: "22"
      VpcId: !Ref VPC
        
  #Creating VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.10.0.0/16

  #Creating Subnet
  PublicSubnet:
    Type: "AWS::EC2::Subnet"
    Properties:
      AvailabilityZone: us-east-1a
      CidrBlock: 10.10.1.0/24
      VpcId: !Ref VPC
  #Associate Route for subnet
  PublicSubnetRouteAss:
    Type: "AWS::EC2::SubnetRouteTableAssociation"  
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref PublicSubnet

  #Create internet Gateway
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  
  #Attach VPC and InternetGateway 
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref 'VPC'
      InternetGatewayId: !Ref 'InternetGateway'
  
  #Create Route Table
  RouteTable:
    Type: "AWS::EC2::RouteTable"
    Properties:
      VpcId: !Ref VPC      

  #Create Public route with Internetgateway 
  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref 'RouteTable'
      DestinationCidrBlock: '0.0.0.0/0'
      GatewayId: !Ref 'InternetGateway'

  #Create Instance  
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'ImageId'
      InstanceType: !Ref 'InstanceType'
      NetworkInterfaces:
      - AssociatePublicIpAddress: true
        DeleteOnTermination: true
        Description: ENI for Linux Instance
        DeviceIndex: '0'
        SubnetId: !Ref 'PublicSubnet'
        GroupSet:
        - !Ref 'SecGrp'
      UserData:
        Fn::Base64: !Sub |
          #!/bash/bin
          sudo yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
          sudo yum-config-manager --enable epel
          sudo yum update
          sudo yum install wget
          sudo mkdir /home/ec2-user/StreamSets
          sudo cd /home/ec2-user/StreamSets
          sudo wget https://archives.streamsets.com/datacollector/2.4.1.0/rpm/streamsets-datacollector-2.4.1.0-all-rpms.tgz
          sudo chmod 777 streamsets-datacollector-2.4.1.0-all-rpms.tgz
          sudo tar -xzf /home/ec2-user/StreamSets/streamsets-datacollector-2.4.1.0-all-rpms.tgz
          sudo cd streamsets-datacollector-2.4.1.0-all-rpms
          sudo yum localinstall -y streamsets*
          sudo cd /etc/security
          sudo chmod 777 limits.conf
          sudo cp limits.conf orig_limits.conf
          sudo echo "*	hard	nofile	33000" > limits.conf
          sudo echo "*	soft	nofile	33000" > limits.conf
          sudo systemctl daemon-reload
          sudo service sdc start
          sudo ssh -N -p 22 ec2-user@10.10.1.0/24 -i /nv.kp.pem -L 18630:localhost:18630 
      Tags:
        - Key: Name
          Value: 'MyInstance'  
        